app/controllers/GalleryController.php
<?php

namespace app\controllers;

use yii\easyii\modules\gallery\api\Gallery;

class GalleryController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionView($slug)
    {
        $album = Gallery::cat($slug);
        if(!$album){
            throw new \yii\web\NotFoundHttpException('Album not found.');
        }

        return $this->render('view', [
            'album' => $album,
            'photos' => $album->photos(['pagination' => ['pageSize' => 4]])
        ]);
    }
}

app/views/gallery/index.php
<?php
use yii\easyii\helpers\Image;
use yii\easyii\modules\gallery\api\Gallery;
use yii\easyii\modules\page\api\Page;
use yii\helpers\Html;
use yii\helpers\Url;

$page = Page::get('page-gallery');

$this->title = $page->seo('title', $page->model->title);
$this->params['breadcrumbs'][] = $page->model->title;
?>
<h1><?= $page->seo('h1', $page->title) ?></h1>
<br/>

<?php foreach(Gallery::cats() as $album) : ?>
    <a class="center-block" href="<?= Url::to(['gallery/view', 'slug' => $album->slug]) ?>">
        <?= Html::img(Image::thumb($album->image, 160, 120)) ?><br/><?= $album->title ?>
    </a>
    <br/>
<?php endforeach; ?>

app/views/gallery/view.php
<?php
use yii\easyii\modules\gallery\api\Gallery;

$this->title = $album->seo('title', $album->model->title);
$this->params['breadcrumbs'][] = ['label' => 'Gallery', 'url' => ['gallery/index']];
$this->params['breadcrumbs'][] = $album->model->title;
?>
<h1><?= $album->seo('h1', $album->title) ?></h1>

<?php if(count($photos)) : ?>
    <div>
        <h4>Photos</h4>
        <?php foreach($photos as $photo) : ?>
            <?= $photo->box(100, 100) ?>
        <?php endforeach;?>
        <?php Gallery::plugin() ?>
    </div>
    <br/>
<?php else : ?>
    <p>Album is empty.</p>
<?php endif; ?>
<?= $album->pages() ?>